stages:
  - build
  - lint
  - test
  - deploy

variables:
  RENDER_API_KEY: $rnd_jsyyCHJRrTKTEaSX92MrwsP0e5UX # Set this in your GitLab CI/CD variables
  SERVICE_ID: $srv-csdnfjlsvqrc7392053g # Set this in your GitLab CI/CD variables

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

lint:
  stage: lint
  image: node:18
  script:
    - npm install
    - npm run lint # Make sure you have a lint script defined in package.json

test:
  stage: test
  image: node:18
  script:
    - npm install
    - npm run test -- --watchAll=false # Ensure tests run in CI mode

deploy:
  stage: deploy
  image: curlimages/curl:7.68.0
  script:
    - 'curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" https://api.render.com/v1/services/$SERVICE_ID/deploys'
  only:
    - main # or the branch you want to deploy from
